version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u db_user -pdb_user_pass"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
